# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ebb2663f9c5b43b2427eec6435adf5d7892519812bfd00c89b7678c321d672402dee560b4a983d0f19c52df09ad90438be35a13195d90cd8b1a8f3034df3bbf6

test:
  secret_key_base: a910500c61fee38fec4de0309922651af5bdfa374f9e7d7d2863cf0f72c4ae60142cbba68dc2601995d4b86a1bda753b0e9d53e9e09994ec4fd37c371e1c4de6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
